# Generated by Django 5.2 on 2025-04-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=20)),
                ('numero_habitacion', models.IntegerField(unique=True)),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
