# Generated by Django 5.2 on 2025-04-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('sencilla', 'Sencilla'), ('doble', 'Doble'), ('triple', 'Triple')], max_length=20),
        ),
    ]
