# Generated by Django 5.2 on 2025-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
    ]
